t3
const int t3::size
const std::string t3::empty
std::string t3::positions[size][size]
std::string t3::ai
std::string t3::player
bool t3::gameOver
bool t3::won
t3::t3()
bool t3::getGameOver()
Referenced by main.
bool t3::getWon()
Referenced by main.
std::string t3::getPosition(int n)
void t3::setPosition(bool isPlayer, int n)
Referenced by main, makeMove.
void t3::printBoard()
Referenced by main.
void t3::checkBoard()
Referenced by main.
void t3::makeMove()
References setPosition.
Referenced by main.
bool t3::spotTaken(int n)
Referenced by main.